project:
  type: website
  output-dir: docs

website:
  title: "Jianyuan(Andy) Hu"
  page-footer: 
    left: Created by Jianyuan(Andy) Hu, 2024 
    right: |
     This book was built with <a href="https://quarto.org/">Quarto</a>.

  repo-url: https://github.com/jy-andy-hu/CamelotCavesInc
  repo-branch: main
  repo-actions: issue

  sidebar: 
    search: false
    tools:
      - icon: linkedin
        href: http://linkedin.com/in/andyhu1
      - icon: github
        href: https://github.com/jy-andy-hu
      - icon: person-square
        href: https://github.com/jy-andy-hu/AllAboutMe

format: 
  html: 
    theme: cerulean
    toc: true
    toc-location: left